import React from 'react'

class Casey extends React.Component{
  render(){return(<div><img src="https://i.pinimg.com/originals/7a/85/c6/7a85c67f3ce783cba6d8bb1844a7ba43.gif" alt="fighting" /><img src="https://64.media.tumblr.com/tumblr_maz1ssLziB1qd4q8ao1_500.gifv" alt="tmnts" /><img src="https://media.giphy.com/media/26DOrkuLu1Jjjq0lG/giphy.gif" alt="grometry" /><img src="https://66.media.tumblr.com/3c3c1ac8ae10b3a0deec4685067d328d/tumblr_pomqubbZSd1scxiy5_540.gif" alt="casey" />< hr /><br /> <section><h3>The src prop passed is </h3><img src={this.props.src} alt="prop" /><br /><h3>The list of quotations passed as props is ...</h3><ol>{this.props.quotes.map(f=><li>{f}</li>)}</ol></section></div>);}
}

function Chiding() {
  return (
    <div>
      <Casey src="https://i.pinimg.com/originals/7a/85/c6/7a85c67f3ce783cba6d8bb1844a7ba43.gif"  quotes={["A mind needs books ans a sword needs whetstone, if it is to keep its edge. Books=the real or ultimate form of socializing, that happens within privacy and solitude! Be led by the dreams in your mind.  I will not let anyone walk through my mind with their dirty feet. Your mind is a palace. Biology gives you brain. You turn it into mind by living.","The mind is not a vessel to be filled, but a fire to be kindled.  It is the presence of mind that makes me unaware of everything else..I am not absentminded.  Mind is stretched by a new idea or sensation, and never shrinks back to its former dimensions. ","If you don't take control of yourself and your own life, someone else is bound to try. Reality exists in the mind and nowhere else. The soul has an interpreter in the eye. Fear kills mind, heart and imagination. I do my best thinking at night, when everyone else is sleeping. No interruptions. No noise. I like the feeling of being awake when no one else is. Reading is to the mind what exercise is to the body.","Mind rebels at stagnation, so does heart wrt body. Give me work and I am in my own proper atmosphere. I crave for mental exaltation. People tend to be generous when sharing their nonsense, fear and ignorance. The diet we need to be on is a spiritual and emotional one. Be cautious with what you feed your mind and soul. Fuel yourself with positivity and let that fuel propel you into positive action.","Its all in the mind. What thoughts are you feeding into your mind. Thoughts create your belief and experiences. Looking at beauty in the world is the first step of purifying the mind. I LIKE LIGHTENING VIDEOS AND TORNADO VIDEOS. Can games our of them, themes. When you make a choice, you change the future." ,"Making decisions is an interplay of the heart and the mind. The heart protests loudly when something is not good for usm and remains silent and at peace when we make the right decision. That is how the heart speaks. There are no loud signals when we do the right things. Success hugs in private....You can never leave a place unless you leave that place in your mind. ","I am the creator of the mind and the thought. A man's capacity is the same as his breadth of vision. Remember to remember! Physical states can be publically known and mental states can only be privatley knowne (physics as coumputaional declations of public and private vars ).Bookworms feed upon the paper's body with their starving minds."]} />
    </div>
  )
}

export default Chiding
